# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desenvolvedor',
            fields=[
                ('pnome', models.CharField(max_length=15)),
                ('snome', models.CharField(max_length=25)),
                ('senha', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=40, primary_key=True, serialize=False)),
                ('cep', models.IntegerField()),
                ('rua', models.CharField(blank=True, max_length=50, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('cidade', models.CharField(blank=True, max_length=30, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('ativo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Telefone_Desenvolvedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.IntegerField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ep3.Desenvolvedor')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='telefone_desenvolvedor',
            unique_together=set([('email', 'telefone')]),
        ),
    ]
