# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 02:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ep3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telefone_Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='telefone_usuario',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ep3.Usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='telefone_usuario',
            unique_together=set([('email', 'telefone')]),
        ),
    ]
