# Generated by Django 2.0 on 2017-12-04 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ep3', '0002_auto_20171204_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelDevProjeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ep3.Desenvolvedor')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ep3.Projeto')),
            ],
        ),
        migrations.RenameModel(
            old_name='RequisitosFuncional',
            new_name='RequisitoFuncional',
        ),
        migrations.AlterUniqueTogether(
            name='reldevprojeto',
            unique_together={('dev_email', 'projeto')},
        ),
    ]
