# Generated by Django 2.0 on 2017-12-05 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ep3', '0003_auto_20171204_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisito',
            name='tipo_req',
        ),
        migrations.AddField(
            model_name='mensagem',
            name='forum',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ep3.Forum'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requisitodados',
            name='descricao',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topico',
            name='status',
            field=models.BooleanField(),
        ),
        migrations.AlterUniqueTogether(
            name='mensagem',
            unique_together={('topico', 'forum')},
        ),
        migrations.AlterUniqueTogether(
            name='requisitodados',
            unique_together={('id', 'requisito')},
        ),
        migrations.AlterUniqueTogether(
            name='requisitofuncional',
            unique_together={('id', 'requisito')},
        ),
    ]
